### ISSUE TITLE
[code][low prio] Assertions in `SortScoreAllTimeTests` too strong

### ISSUE THREAD

**Issue by Jakob-Bach** [bendixsonnenberg/CS-Select#125]
Only the order should be tested (and maybe that the number of points of particular players did not change during sorting), but not how quality scores passed to `finishRound()` affect the exact amount of points in the leaderboard (that's not the responsibility of a sorting strategy).

**Comment by Jakob-Bach** [comment]
Similar problem appears in `PlayerStatsTests`, where round scores are manually computed instead of comparing against `commuteScore()` (which has no own tests).

**Comment by Santaaa348** [comment]
I adjusted the tests in `SortScoreAllTimeTest`. 
The `commuteScore` method is private, hence there are no own tests, however it is part of `finishRound` which has multiple tests. 
I do not see a way around the manual comparisons though (since `commuteScore` is private). Basically some of the tests only test getters. Maybe I could remove them?

**Comment by Jakob-Bach** [comment]
`SortScoreAllTimeTest` is fine now. I would increase the accessibility of `commuteScore` (which should be renamed to `computeScore)` to package or protected for better testability. As far as I can see, the individual in test cases in `PlayerStats` make sense, the only should not contain the hard-coded scores (apart from a dedicated test for `commuteScore`). If one would change the scoring mechanism (e.g., multiply with 10 instead of 100), all test cases would have to be adapted with the current implementation.
