### ISSUE TITLE
[bug] Leaderboard points can be different to player points

### ISSUE THREAD

**Issue by Jakob-Bach** [bendixsonnenberg/CS-Select#158]
![screenshot](https://user-images.githubusercontent.com/6431179/52559964-2ad0a680-2df7-11e9-8005-55bf7b104b57.PNG)

Don't know how this happened exactly. Played rounds from two or three games, logged in and out several times. Currently two games are active, but there was also one before which I deleted (and I'm not sure if I played it with this player) - maybe deletion can cause that difference in scores.

**Comment by SeineEloquenz** [comment]
Deletion does and should cause a reduction in points when using points of the last week, as we determine the points from the played rounds which obviously aren't accessible anymore if the game is deleted.
For the all-time-Leaderboard this should not happen as player points are indifferent to game deletion so the all-time-Leaderboard should be as well.

**Comment by Santaaa348** [comment]
This leaderboard shows the score of the last week (I will add a header for that, so that the player knows). Since the points shown below the username represent the total score, the difference is supposed to happen. Did you have a round older than a week?
As mentioned above, if you delete games/rounds from the database the leaderboard (lastWeek) would not recover the points correctly.

**Comment by Jakob-Bach** [comment]
I did not have an old round, but probably a deleted game. Once the leaderboard has a new header (and the player score label should probably also get a description/tooltip saying it show the total score), this issue can be closed.
