### ISSUE TITLE
[feature-request][low prio] Add language picker on login page

### ISSUE THREAD

**Issue by Jakob-Bach** [bendixsonnenberg/CS-Select#86]
Not that important as fields on login form are straightforward, but would still be nice.

**Comment by bendixsonnenberg** [comment]
quite hard to do with the current way of loading localisation, unless the page is reloaded.

**Comment by SeineEloquenz** [comment]
@bendixsonnenberg says we don't fix this because this change doesn't provide a significant improvement for the user experience for the amount of changes that would be necessary to implement this and we'd need a second mechanism for localising strings in the frontend, which would increase maintenance overhead
